FROM ubuntu:16.04


RUN apt-get update && apt-get install sudo  curl  wget -y



# 配置普通用户
RUN useradd --create-home --no-log-init --shell /bin/bash docker \
&& adduser docker sudo \
&& echo 'docker:123456' | chpasswd

# 安装配置 fixuid
RUN USER=docker && \
        GROUP=docker && \
        curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.4.1/fixuid-0.4.1-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - && \
        chown root:root /usr/local/bin/fixuid && \
        chmod 4755 /usr/local/bin/fixuid && \
        mkdir -p /etc/fixuid && \
        printf "user: $USER\ngroup: $GROUP\n" > /etc/fixuid/config.yml

USER docker:docker
ENTRYPOINT ["fixuid"]
# 设置文件夹
RUN mkdir -p /home/docker/file
RUN chmod -R 777 /home/docker/file
RUN chown -R docker:docker /home/docker/file
WORKDIR /home/docker
CMD /bin/bash
