FROM ubuntu:18.04

RUN apt-get update 

RUN apt-get install sudo -y
RUN apt-get install make  -y
# 之后手动安装 RUN apt-get install unrar-free  -y
RUN apt-get install autoconf  -y
RUN apt-get install automake  -y
RUN apt-get install libtool  -y
RUN apt-get install gcc  -y
RUN apt-get install g++  -y
RUN apt-get install gperf   -y
RUN apt-get install flex  -y
RUN apt-get install bison  -y
RUN apt-get install texinfo  -y
RUN apt-get install gawk  -y
RUN apt-get install ncurses-dev  -y
RUN apt-get install libexpat-dev  -y
RUN apt-get install python-dev  -y
RUN apt-get install python  -y
RUN apt-get install python-serial  -y 
RUN apt-get install sed  -y
RUN apt-get install git  -y
RUN apt-get install unzip  -y
RUN apt-get install bash  -y
RUN apt-get install help2man -y 
RUN apt-get install wget  -y
RUN apt-get install bzip2 -y

RUN useradd --create-home --no-log-init --shell /bin/bash docker \
&& adduser docker sudo \
&& echo 'docker:123456' | chpasswd

USER docker:docker

CMD /bin/bash


